language: cpp

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
          packages: ['clang-5.0', 'libstdc++-8-dev']
      env: COMPILER='clang++-5.0'


    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
          packages: ['clang-6.0', 'libstdc++-8-dev']
      env: COMPILER='clang++-6.0'

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: COMPILER='g++-7'

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env: COMPILER='g++-8'


before_script:
  - export CXX=${COMPILER}
  - ./autogen.sh

script:
  - ./configure --prefix=/home/travis/fuxbin && make && make check
  - make install && make installcheck

branches:
  only:
    - master
